// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authQueryService.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenTokenRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenTokenRequest) Reset()         { *m = GenTokenRequest{} }
func (m *GenTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GenTokenRequest) ProtoMessage()    {}
func (*GenTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d8887b8ada7f038, []int{0}
}

func (m *GenTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenTokenRequest.Unmarshal(m, b)
}
func (m *GenTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenTokenRequest.Marshal(b, m, deterministic)
}
func (m *GenTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenTokenRequest.Merge(m, src)
}
func (m *GenTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GenTokenRequest.Size(m)
}
func (m *GenTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenTokenRequest proto.InternalMessageInfo

func (m *GenTokenRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GenTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenTokenResponse) Reset()         { *m = GenTokenResponse{} }
func (m *GenTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GenTokenResponse) ProtoMessage()    {}
func (*GenTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d8887b8ada7f038, []int{1}
}

func (m *GenTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenTokenResponse.Unmarshal(m, b)
}
func (m *GenTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenTokenResponse.Marshal(b, m, deterministic)
}
func (m *GenTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenTokenResponse.Merge(m, src)
}
func (m *GenTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GenTokenResponse.Size(m)
}
func (m *GenTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenTokenResponse proto.InternalMessageInfo

func (m *GenTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GenTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*GenTokenRequest)(nil), "auth.GenTokenRequest")
	proto.RegisterType((*GenTokenResponse)(nil), "auth.GenTokenResponse")
}

func init() { proto.RegisterFile("authQueryService.proto", fileDescriptor_7d8887b8ada7f038) }

var fileDescriptor_7d8887b8ada7f038 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2c, 0x2d, 0xc9,
	0x08, 0x2c, 0x4d, 0x2d, 0xaa, 0x0c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x2b, 0xa9, 0x72, 0xf1, 0xbb, 0xa7, 0xe6, 0x85, 0xe4, 0x67,
	0xa7, 0xe6, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x94, 0x96, 0x66,
	0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x11, 0x5c, 0x02, 0x08, 0x65,
	0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x0a, 0x5c, 0xdc, 0x89, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5,
	0x60, 0x61, 0xa8, 0x72, 0x64, 0x21, 0x21, 0x25, 0x2e, 0x9e, 0xa2, 0xd4, 0xb4, 0xa2, 0xd4, 0xe2,
	0x0c, 0x88, 0x12, 0x26, 0xb0, 0x12, 0x14, 0x31, 0x23, 0x7f, 0x2e, 0x01, 0x47, 0x34, 0x07, 0x0a,
	0x59, 0x73, 0x71, 0xc0, 0x6c, 0x13, 0x12, 0xd5, 0x03, 0xb9, 0x53, 0x0f, 0xcd, 0x91, 0x52, 0x62,
	0xe8, 0xc2, 0x10, 0x47, 0x29, 0x31, 0x24, 0xb1, 0x81, 0xbd, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x63, 0x3d, 0xa7, 0xe2, 0xf8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthQueryServiceClient is the client API for AuthQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthQueryServiceClient interface {
	GenToken(ctx context.Context, in *GenTokenRequest, opts ...grpc.CallOption) (*GenTokenResponse, error)
}

type authQueryServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthQueryServiceClient(cc *grpc.ClientConn) AuthQueryServiceClient {
	return &authQueryServiceClient{cc}
}

func (c *authQueryServiceClient) GenToken(ctx context.Context, in *GenTokenRequest, opts ...grpc.CallOption) (*GenTokenResponse, error) {
	out := new(GenTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthQueryService/GenToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthQueryServiceServer is the server API for AuthQueryService service.
type AuthQueryServiceServer interface {
	GenToken(context.Context, *GenTokenRequest) (*GenTokenResponse, error)
}

// UnimplementedAuthQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthQueryServiceServer struct {
}

func (*UnimplementedAuthQueryServiceServer) GenToken(ctx context.Context, req *GenTokenRequest) (*GenTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenToken not implemented")
}

func RegisterAuthQueryServiceServer(s *grpc.Server, srv AuthQueryServiceServer) {
	s.RegisterService(&_AuthQueryService_serviceDesc, srv)
}

func _AuthQueryService_GenToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthQueryServiceServer).GenToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthQueryService/GenToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthQueryServiceServer).GenToken(ctx, req.(*GenTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthQueryService",
	HandlerType: (*AuthQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenToken",
			Handler:    _AuthQueryService_GenToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authQueryService.proto",
}
